name: CI - Test Source Code and Docker Image

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  # Step 2: Build Docker Image
  build-docker-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use the token here

      - name: Build Docker Image
        working-directory: ./api
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/savetofocus_backend:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/savetofocus_backend:latest
        
  build-docker-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use the token here

      - name: Build Docker Image back
        working-directory: ./client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/savetofocus_frontend:latest .

      - name: Push Docker Image to DockerHub
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/savetofocus_frontend:latest
  # Step 3: Test Docker Image
  # test-docker-image:
  #   # needs: [build-docker-back,build-docker-front]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Log in to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }} # Use the token here
  #     - name: Create Custom Network
  #       run: |
  #         docker network create my_network

  #     - name: Pull and Run Docker Image Backend
  #       run: |
  #         docker pull ${{ secrets.DOCKER_USERNAME }}/savetofocus_backend:latest
  #         docker run -d \
  #         --name backend \
  #         ${{ secrets.DOCKER_USERNAME }}/savetofocus_backend:latest

  #     - name: Run Automated Tests in Docker Container
  #       run: |
  #         docker exec backend yarn test 

  #     - name: Clean Up Docker Container
  #       run: |
  #         docker stop backend
  #         docker rm backend
